FROM golang:1.25-alpine AS build

WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY api ./api
COPY cmd ./cmd
COPY internal ./internal
RUN CGO_ENABLED=0 go build -trimpath -ldflags='-s -w' -o /out/bridge-master ./cmd/bridge-master

FROM alpine:3.22
RUN apk add --no-cache ca-certificates
COPY --from=build /out/bridge-master /usr/local/bin/bridge-master
ENTRYPOINT ["/usr/local/bin/bridge-master"]
